name: Deploy to Server

on:
  push:
    branches:
      - master

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_ID_RSA }}
          known_hosts: ${{ secrets.KNOWN_HOST }}
          host: ${{ secrets.DEPLOY_SERVER_IP }}

      - name: Deploy application
        run: |
          ssh ${{ vars.SSH_HOST }} << 'ENDSSH'
            mkdir -p ${{ vars.DEPLOY_APP_PATH }}
            mkdir -p ${{ vars.DEPLOY_APP_LOG_PATH }}          
            cd ${{ vars.DEPLOY_APP_PATH }} # 进入你的应用目录
            sudo systemctl stop ${{ vars.DEPLOY_SERVICE_NAME }} # 停止现有服务
            rm -rf * # 删除旧的应用程序文件
            exit
          ENDSSH
          
          scp target/*.jar ${{ vars.SSH_HOST }}:${{ vars.DEPLOY_APP_PATH }}
          
          ssh ${{ vars.SSH_HOST }} << 'ENDSSH'

            # 检查文件是否存在，如果不存在则创建
            if [ ! -f ${{ vars.APPLICATION_ENV_PATH }} ]; then
            echo "Creating application.env file..."
            touch ${{ vars.APPLICATION_ENV_PATH }}
            fi

            cd ${{ vars.DEPLOY_APP_PATH }}
            echo "SERVER_PORT=${{ vars.SERVER_PORT }}" > ${{ vars.APPLICATION_ENV_PATH }}
            echo "DATASOURCE_URL=${{ vars.DATASOURCE_URL }}" >> ${{ vars.APPLICATION_ENV_PATH }}
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> ${{ vars.APPLICATION_ENV_PATH }}
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ${{ vars.APPLICATION_ENV_PATH }}
            echo "LOGGING_FILE_PATH=${{ vars.LOGGING_FILE_PATH }}" >> ${{ vars.APPLICATION_ENV_PATH }}
            
            # 启动服务
            sudo systemctl start ${{ vars.DEPLOY_SERVICE_NAME }}
          
            # 检查服务是否成功启动
            sleep 5 # 等待服务启动完成
            if sudo systemctl is-active --quiet ${{ vars.DEPLOY_SERVICE_NAME }}; then
            echo "Service started successfully."
            # 删除 application.env 文件
            rm -f ${{ vars.APPLICATION_ENV_PATH }}
            echo "Deleted application.env file."
            else
            echo "Failed to start service. Keeping application.env for debugging."
            exit 1
            fi
          
            exit
          ENDSSH